name: Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1/${{ runner.os }}/node-14/${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1/${{ runner.os }}/node-14/
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
      - name: Percy run
        uses: percy/exec-action@v0.3.1
        with:
          custom-command: "npm run percy:test"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
